### ISSUE TITLE
Does not match all combinations of emojis that support multiple skin tones

### ISSUE THREAD

**Issue by scriby** [mathiasbynens/emoji-regex#65]
For instance, the regex will match 🧑🏼‍🤝‍🧑🏻 (`'\u{1F9D1}\u{1F3FC}\u200D\u{1F91D}\u200D\u{1F9D1}\u{1F3FB}'`), but it doesn't match  🧑🏻‍🤝‍🧑🏼 (`'\u{1F9D1}\u{1F3FB}\u200D\u{1F91D}\u200D\u{1F9D1}\u{1F3FC}'`). It seems to only work if the darker skin tone is on the left side. There are some more emojis that support multiple skin tones coming, so it would be great if this could match against all possible combinations.

**Comment by scriby** [comment]
It looks like this issue is resolved in Unicode 12.1 where both combinations are in the RGI.

**Comment by JuanCarlosC** [comment]
@scriby I am still experiencing the same issue where it will only work if the darker skin tone is on the left side. Did you find a solution?

I've used the `inject-sequences.js` script to update the regular expression based on the data from Unicode v12, but still seeing the same issue.

<img width="283" alt="Screen Shot 2020-02-25 at 8 03 45 PM" src="https://user-images.githubusercontent.com/7284135/75310901-00873680-580a-11ea-995a-581ad1024134.png">

**Comment by scriby** [comment]
Supporting the darker skin tones on the left was included in Unicode 12.1.
So if you’re running against v12 they won’t work.

**Comment by JuanCarlosC** [comment]
@scriby updated my comment above. Yes, I ran this script against 12.1. Are you no longer experiencing the issue?

**Comment by scriby** [comment]
I ended up stopping using this library since it wasn’t clear when it would
be updated, so I don’t know if it works properly or not when ran against
12.1. But it seems like it should work... Maybe double-check your
node_modules to make sure it’s running against the right version of Unicode?

**Comment by mathiasbynens** [comment]
If I understand the issue correctly, it looks like this has already been fixed when I updated to the latest Unicode version:

```
$ node -p "require('emoji-regex')().exec('\u{1F9D1}\u{1F3FC}\u200D\u{1F91D}\u200D\u{1F9D1}\u{1F3FB}')"
[ '🧑🏼‍🤝‍🧑🏻', index: 0, input: '🧑🏼‍🤝‍🧑🏻', groups: undefined ]

$ node -p "require('emoji-regex')().exec('\u{1F9D1}\u{1F3FB}\u200D\u{1F91D}\u200D\u{1F9D1}\u{1F3FC}')"
[ '🧑🏻‍🤝‍🧑🏼', index: 0, input: '🧑🏻‍🤝‍🧑🏼', groups: undefined ]
```

@scriby Can you confirm this is now behaving as you expected?

**Comment by mathiasbynens** [comment]
Closing since I believe this has been resolved. Feel free to reopen if I misunderstood.
